name: Deploy Docker Secret

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Docker Secret
        run: |
          echo "${{ secrets.APP_CONFIG }}" | docker secret create app_config -
