name: Deploy Docker Secret

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Docker secret
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SWARM_HOST }}
          username: ${{ secrets.SWARM_USER }}
          key: ${{ secrets.SWARM_SSH_KEY }}
          script: |
            if docker secret inspect app_config >/dev/null 2>&1; then
              docker secret rm app_config
            fi
            echo '${{ secrets.APP_CONFIG }}' | docker secret create app_config -
            docker stack deploy -c docker-compose.yml myapp
